spring.application.name=finance-dashboard

# Server configuration
server.port=8080

# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/finance_dashboard?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
# Update username/password based on actual MySQL instance

# JPA/Hibernate Properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# JWT Configuration
jwt.secret=94a08da1fecbb6e8b46990538c7b50b2a8d11d141e6a17b6a482b8146747192a
jwt.expiration=86400000

# To prevent Jackson serialization issues
spring.jackson.serialization.fail-on-empty-beans=false
